//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemnantSaveGuardian.locales {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemnantSaveGuardian.locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Remnant Save Guardian 的本地化字符串。
        /// </summary>
        public static string AboutRSG {
            get {
                return ResourceManager.GetString("AboutRSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adventure 的本地化字符串。
        /// </summary>
        public static string Adventure {
            get {
                return ResourceManager.GetString("Adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete backup {backupName}? 的本地化字符串。
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_backup__backupName__ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete backup {backupName}?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup completed 的本地化字符串。
        /// </summary>
        public static string Backup_completed {
            get {
                return ResourceManager.GetString("Backup completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Folder 的本地化字符串。
        /// </summary>
        public static string Backup_Folder {
            get {
                return ResourceManager.GetString("Backup Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup folder not set; reverting to default. 的本地化字符串。
        /// </summary>
        public static string Backup_folder_not_set__reverting_to_default_ {
            get {
                return ResourceManager.GetString("Backup folder not set; reverting to default.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup restored 的本地化字符串。
        /// </summary>
        public static string Backup_restored {
            get {
                return ResourceManager.GetString("Backup restored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backups folder not found, creating... 的本地化字符串。
        /// </summary>
        public static string Backups_folder_not_found__creating___ {
            get {
                return ResourceManager.GetString("Backups folder not found, creating...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backups found 的本地化字符串。
        /// </summary>
        public static string Backups_found {
            get {
                return ResourceManager.GetString("Backups found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup current save 的本地化字符串。
        /// </summary>
        public static string btnBackup_ToolTip {
            get {
                return ResourceManager.GetString("btnBackup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Now 的本地化字符串。
        /// </summary>
        public static string btnCheckUpdate_Content {
            get {
                return ResourceManager.GetString("btnCheckUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open backups folder 的本地化字符串。
        /// </summary>
        public static string btnOpenBackupsFolder_ToolTip {
            get {
                return ResourceManager.GetString("btnOpenBackupsFolder_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start game 的本地化字符串。
        /// </summary>
        public static string btnStartGame_ToolTip {
            get {
                return ResourceManager.GetString("btnStartGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Campaign 的本地化字符串。
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string Character {
            get {
                return ResourceManager.GetString("Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Characters 的本地化字符串。
        /// </summary>
        public static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically backup save files 的本地化字符串。
        /// </summary>
        public static string chkAutoBackup_Content {
            get {
                return ResourceManager.GetString("chkAutoBackup_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor Remnant save files and back them up when they&apos;re changed 的本地化字符串。
        /// </summary>
        public static string chkAutoBackup_ToolTip {
            get {
                return ResourceManager.GetString("chkAutoBackup_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically check for program update 的本地化字符串。
        /// </summary>
        public static string chkAutoCheckUpdate_Content {
            get {
                return ResourceManager.GetString("chkAutoCheckUpdate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create log file 的本地化字符串。
        /// </summary>
        public static string chkCreateLogFile_Content {
            get {
                return ResourceManager.GetString("chkCreateLogFile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether a log.txt file should be created 的本地化字符串。
        /// </summary>
        public static string chkCreateLogFile_ToolTip {
            get {
                return ResourceManager.GetString("chkCreateLogFile_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Possible Items column in analyzer 的本地化字符串。
        /// </summary>
        public static string chkShowPossibleItems_Content {
            get {
                return ResourceManager.GetString("chkShowPossibleItems_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a backup to restore from the list. 的本地化字符串。
        /// </summary>
        public static string Choose_a_backup_to_restore_from_the_list_ {
            get {
                return ResourceManager.GetString("Choose a backup to restore from the list.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        public static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find save file location; please set manually 的本地化字符串。
        /// </summary>
        public static string Could_not_find_save_file_location__please_set_manually {
            get {
                return ResourceManager.GetString("Could not find save file location; please set manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting excess backup 的本地化字符串。
        /// </summary>
        public static string Deleting_excess_backup {
            get {
                return ResourceManager.GetString("Deleting excess backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to move your backups to this new folder? 的本地化字符串。
        /// </summary>
        public static string Do_you_want_to_move_your_backups_to_this_new_folder_ {
            get {
                return ResourceManager.GetString("Do you want to move your backups to this new folder?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error checking for new game info 的本地化字符串。
        /// </summary>
        public static string Error_checking_for_new_game_info {
            get {
                return ResourceManager.GetString("Error checking for new game info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error checking for new version 的本地化字符串。
        /// </summary>
        public static string Error_checking_for_new_version {
            get {
                return ResourceManager.GetString("Error checking for new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the game before restoring a save backup. 的本地化字符串。
        /// </summary>
        public static string Exit_the_game_before_restoring_a_save_backup_ {
            get {
                return ResourceManager.GetString("Exit the game before restoring a save backup.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export save files 的本地化字符串。
        /// </summary>
        public static string Export_save_files_as_plaintext {
            get {
                return ResourceManager.GetString("Export save files as plaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Folder 的本地化字符串。
        /// </summary>
        public static string Game_Folder {
            get {
                return ResourceManager.GetString("Game Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game info updated. 的本地化字符串。
        /// </summary>
        public static string Game_info_updated_ {
            get {
                return ResourceManager.GetString("Game info updated.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardcore 的本地化字符串。
        /// </summary>
        public static string Hardcore {
            get {
                return ResourceManager.GetString("Hardcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid backup restore type 的本地化字符串。
        /// </summary>
        public static string Invalid_backup_restore_type {
            get {
                return ResourceManager.GetString("Invalid backup restore type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Folder 的本地化字符串。
        /// </summary>
        public static string Invalid_Folder {
            get {
                return ResourceManager.GetString("Invalid Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid folder: Backup folder cannot be the game&apos;s save folder. 的本地化字符串。
        /// </summary>
        public static string InvalidBackupFolderNoBackupsInSaves {
            get {
                return ResourceManager.GetString("InvalidBackupFolderNoBackupsInSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid folder: Select where your Remnant II game is installed. 的本地化字符串。
        /// </summary>
        public static string InvalidGameFolder {
            get {
                return ResourceManager.GetString("InvalidGameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid folder: Select where your Remnant II saves are stored 的本地化字符串。
        /// </summary>
        public static string InvalidSaveFolder {
            get {
                return ResourceManager.GetString("InvalidSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid folder: Please select a folder other than the backup folder. 的本地化字符串。
        /// </summary>
        public static string InvalidSaveFolderNoSavesInBackups {
            get {
                return ResourceManager.GetString("InvalidSaveFolderNoSavesInBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep 的本地化字符串。
        /// </summary>
        public static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last backup save date 的本地化字符串。
        /// </summary>
        public static string Last_backup_save_date {
            get {
                return ResourceManager.GetString("Last backup save date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backups to keep (0 for unlimited) 的本地化字符串。
        /// </summary>
        public static string lblBackupLimit_Text {
            get {
                return ResourceManager.GetString("lblBackupLimit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When your number of backups reaches this number, backups will automatically be deleted starting with the oldest 的本地化字符串。
        /// </summary>
        public static string lblBackupLimit_ToolTip {
            get {
                return ResourceManager.GetString("lblBackupLimit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes between backups 的本地化字符串。
        /// </summary>
        public static string lblBackupMins_Text {
            get {
                return ResourceManager.GetString("lblBackupMins_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum amount of time that must have passed since last backup before a new backup is made 的本地化字符串。
        /// </summary>
        public static string lblBackupMins_ToolTip {
            get {
                return ResourceManager.GetString("lblBackupMins_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World analzyer missing item color 的本地化字符串。
        /// </summary>
        public static string lblMissingItemColor_Content {
            get {
                return ResourceManager.GetString("lblMissingItemColor_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start page 的本地化字符串。
        /// </summary>
        public static string lblStartPage_Text {
            get {
                return ResourceManager.GetString("lblStartPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Which page to load on app start 的本地化字符串。
        /// </summary>
        public static string lblStartPage_ToolTip {
            get {
                return ResourceManager.GetString("lblStartPage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Backup 的本地化字符串。
        /// </summary>
        public static string menuRestore_Header {
            get {
                return ResourceManager.GetString("menuRestore_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything 的本地化字符串。
        /// </summary>
        public static string menuRestoreAll_Header {
            get {
                return ResourceManager.GetString("menuRestoreAll_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Characters Only 的本地化字符串。
        /// </summary>
        public static string menuRestoreCharacters_Header {
            get {
                return ResourceManager.GetString("menuRestoreCharacters_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Worlds Only 的本地化字符串。
        /// </summary>
        public static string menuRestoreWorlds_Header {
            get {
                return ResourceManager.GetString("menuRestoreWorlds_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Items 的本地化字符串。
        /// </summary>
        public static string Missing_Items {
            get {
                return ResourceManager.GetString("Missing Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Backups 的本地化字符串。
        /// </summary>
        public static string Move_Backups {
            get {
                return ResourceManager.GetString("Move Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version available! 的本地化字符串。
        /// </summary>
        public static string New_version_available_ {
            get {
                return ResourceManager.GetString("New version available!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        public static string Open_Folder {
            get {
                return ResourceManager.GetString("Open Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open wiki 的本地化字符串。
        /// </summary>
        public static string Open_wiki {
            get {
                return ResourceManager.GetString("Open wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Possible Items 的本地化字符串。
        /// </summary>
        public static string Possible_Items {
            get {
                return ResourceManager.GetString("Possible Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferences 的本地化字符串。
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 processing save file change 的本地化字符串。
        /// </summary>
        public static string processing_save_file_change {
            get {
                return ResourceManager.GetString("processing save file change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progression 的本地化字符串。
        /// </summary>
        public static string Progression {
            get {
                return ResourceManager.GetString("Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Backups 的本地化字符串。
        /// </summary>
        public static string Save_Backups {
            get {
                return ResourceManager.GetString("Save Backups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save change detected; waiting {numMinutes} minutes until next backup 的本地化字符串。
        /// </summary>
        public static string Save_change_detected__waiting__numMinutes__minutes_until_next_backup {
            get {
                return ResourceManager.GetString("Save change detected; waiting {numMinutes} minutes until next backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save file in use; waiting 0.5 seconds and retrying. 的本地化字符串。
        /// </summary>
        public static string Save_file_in_use__waiting_0_5_seconds_and_retrying_ {
            get {
                return ResourceManager.GetString("Save file in use; waiting 0.5 seconds and retrying.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Folder 的本地化字符串。
        /// </summary>
        public static string Save_Folder {
            get {
                return ResourceManager.GetString("Save Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save plaintext data 的本地化字符串。
        /// </summary>
        public static string Save_plaintext_data {
            get {
                return ResourceManager.GetString("Save plaintext data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Date 的本地化字符串。
        /// </summary>
        public static string SaveDate {
            get {
                return ResourceManager.GetString("SaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saves 的本地化字符串。
        /// </summary>
        public static string Saves {
            get {
                return ResourceManager.GetString("Saves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a folder other than the game&apos;s save folder. 的本地化字符串。
        /// </summary>
        public static string Select_a_folder_other_than_the_game_s_save_folder_ {
            get {
                return ResourceManager.GetString("Select a folder other than the game\'s save folder.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 setting save file timer 的本地化字符串。
        /// </summary>
        public static string setting_save_file_timer {
            get {
                return ResourceManager.GetString("setting save file timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Survival 的本地化字符串。
        /// </summary>
        public static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string Text_Highlight {
            get {
                return ResourceManager.GetString("Text_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string Text_Normal {
            get {
                return ResourceManager.GetString("Text_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 World Analyzer 的本地化字符串。
        /// </summary>
        public static string World_Analyzer {
            get {
                return ResourceManager.GetString("World Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter by events or items 的本地化字符串。
        /// </summary>
        public static string WorldAnalyzerFilter_PlaceholderText {
            get {
                return ResourceManager.GetString("WorldAnalyzerFilter_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must wait 5 minutes between update checks 的本地化字符串。
        /// </summary>
        public static string You_must_wait_5_minutes_between_update_checks {
            get {
                return ResourceManager.GetString("You must wait 5 minutes between update checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
